### PR TITLE
[Feat] Create zh-TW version and contain questions 1-15

### PR DESCRIPTION
**Pull request by askiebaby**
Hi Lydia,

#### This is a draft PR containing two things:
- Created a zh-TW version from Taiwan
- Finished questions 1-15 for translation

Thank you.

### CODE REVIEW

**Comment by lydiahallie** [comment]
Thanks! Let me know when I can merge the first questions or if you'd rather keep on working on it before I merge

**Comment by lydiahallie** [comment]
Hey, any news here? 😊

**Comment by askiebaby** [comment]
Hi Lydia, I am busy on my new job and handling cases recently, so I have no time to translate it. BUT, I will continuously translate the rest questions in the next 2 month. Thank you for reminding me :)

**Comment by lydiahallie** [comment]
No problem at all, I really appreciate your input so far! 

If it's okay with you, I'll merge the changes that you've made so far. It would be great if you could add a link to this translation in `en-EN/README.md` as well, currently it's only in `README.md` 😃

**Comment by askiebaby** [comment]
Ok, I will add a  link in `en-EN/README.md` ^______^!

**Pull request merged**
