### PR TITLE
Translate into Spanish🇪🇸

### PR DESCRIPTION
**Pull request by aguadotzn**
Work in progress.

### CODE REVIEW

**Comment by JesusMurF** [comment]
Hey! I started translating into spanish today because I didn't see this pull request so I will stop translating but if you need some help don't be shy and tell me 👍

**Comment by aguadotzn** [comment]
Hello! ok @JesusMurF, thanks! Do you want to translate from 30 to 41? I´m right now doing 24th question. Let me know :)

**Comment by JesusMurF** [comment]
It will be a mess because I dont have access to your ES file until Lydia accept your pull request, it will be better if you finish the translation 😊

**Comment by aguadotzn** [comment]
yes u are right! I will finish it. I'm planning that will be ready for tomorrow. Then you can review it that for sure I will do some mistakes :)

**Comment by lydiahallie** [comment]
Hey, I see you changed it to a regular PR.  Is the translation finished?

**Comment by aguadotzn** [comment]
Yes!  I saw that you add more questions. You can merge this PRQ and I'll open another one with new translations (or also other people can work on it, maybe @JesusMurF is interested too)

**Pull request merged**
