### PR TITLE
persian translation

### PR DESCRIPTION
**Pull request by alinaserinet**
started persian translation  and translate description, questions 1-4

### CODE REVIEW

**Review by Duc56789 — APPROVED** [review]

**Review by Duc56789 — APPROVED** [review]

**Review by Duc56789 — APPROVED** [review]

**Review by Duc56789 — APPROVED** [review]

**Comment by Duc56789** [comment]
Hù

**Review by Duc56789 — APPROVED** [review]

**Review by Duc56789 — COMMENTED** [review]
Bfgđy

**Review by Duc56789 — APPROVED** [review]

**Review by Duc56789 — COMMENTED** [review]
Huỳ

**Comment by jakeherp** [comment]
Closing due to inactivity

**Pull request closed without merging**
