### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlexxBoro**
just a few typos corrected

### CODE REVIEW

**Comment by lydiahallie** [comment]
Thanks! Could you maybe also update this in `en/README.md` so they're both in sync? :)

**Review by lydiahallie — CHANGES_REQUESTED** [review]
Could you maybe also update this in the root `README.md` so they're both in sync? :)

**Comment by roderohan** [comment]
> just a few typos corrected

I don't know how to use this app please tell me!

**Comment by jakeherp** [comment]
Closing for inactivity, please feel free to reopen when the above is resolved.

**Pull request closed without merging**
