### PR TITLE
Fix question 92 and remove duplicate of 92

### PR DESCRIPTION
**Pull request by srijanshetty**

### CODE REVIEW

**Comment by srijanshetty** [comment]
This is a fix for #197 and #196

**Comment by lydiahallie** [comment]
Woah thanks,  I must have been tired yesterday hahaha! Could you maybe also fix this in the `en-EN/README.md`?

**Comment by lydiahallie** [comment]
Merged it and fixed it in `en-EN/README.md` to avoid confusion 👍

**Comment by srijanshetty** [comment]
Hey @lydiahallie, got caught up in a meeting. Will update both those README.md going forward.

**Pull request merged**
