### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by Eomm**
Hi, 
I'm starting the translation of this awesome work in Italian.

I'm opening this draft-PR to avoid duplicate works: if someone would like to help me go faster I would be glad 👍

### CODE REVIEW

**Comment by lydiahallie** [comment]
Great work! Can I merge this?

**Comment by Eomm** [comment]
I don't finish yet, I can speed up a little bit 💪

**Comment by lydiahallie** [comment]
I'll close this PR now due to inactivity. If it's still an issue, feel free to reopen it! 😃

**Comment by Eomm** [comment]
Yes, sorry.

I will reopen it when complete it 👍

**Pull request closed without merging**
