### PR TITLE
Question 98 little mistake corrected

### PR DESCRIPTION
**Pull request by Alireza29675**

### CODE REVIEW

**Review by lucalves — APPROVED** [review]

**Review by jakeherp — COMMENTED** [review]
@lydiahallie I believe this question needs to be changed, since it does in fact throw a `SyntaxError` because in a function body you wouldn't just assign a value, you'd need to set `name` and `age` as variables and assign the value of `user.name` and `user.age` to those. 

With this throwing a SyntaxError on the definition of the `getUser` function, I am not sure how valuable this question really is.

**Comment by raduflp** [comment]
@jakeherp would this be more appropriate?
```js
const getList = ([x, ...y]) => [x, y]

const list = [1, 2, 3, 4]
console.log(getList(list))

const getUser = user => { name: user.name, age: user.age }

const user = { name: "Lydia", age: 21 }
console.log(getUser(user))

```

Answer A:  `[1, [2, 3, 4]]` and `SyntaxError`

**Review by jaexsb — APPROVED** [review]

**Review by Zcoding4mer — COMMENTED** [review]
option A is  `SyntaxError`  just fine , the reason needed shows under the options

**Review by jaexsb — COMMENTED** [review]
All I know is préstamos & I have a contract for $5,200 that they never delivered on, nor will they respond to any of my requests

**Comment by jaexsb** [comment]
Is this supposed to be in ‘coding’ language? That would severely limit my ability to communicate

**Comment by jakeherp** [comment]
Closing as outdated

**Pull request closed without merging**
