### PR TITLE
Add translation to Thai

### PR DESCRIPTION
**Pull request by sureemo**
- Start with introduction and questions

### CODE REVIEW

**Comment by lydiahallie** [comment]
Thank you so much for your input! Could you please add the link in the `en-EN/README.md` as well? :)

**Comment by sureemo** [comment]
> 
> 
> Thank you so much for your input! Could you please add the link in the `en-EN/README.md` as well? :)

Thank you for comment. I have add the link and update links in other language. Kindly review and feedback me if any concern. Thank you again ^_^

**Comment by contributorpw** [comment]
@sureemo It was a cheat! Don't touch good files! Think before please.

@lydiahallie You have a leak. You do not have time to check the validity.

**Comment by sureemo** [comment]
@contributorpw 
- Just fix the broken links sorry if it's not good to do, I will revert change if you concern.
- For the translation, just done for question and I'm translating the answer to have all more completed.
- Thank you for review and comment. I will improve.

**Comment by contributorpw** [comment]
@sureemo 

Thanks for the reply. It's fine.

Sorry if I was rude. English is not my native language.

**Pull request merged**
