### PR TITLE
Arabic Translation 

### PR DESCRIPTION
**Pull request by SaraAli26**
Starting from question 4 until the last question.

### CODE REVIEW

**Comment by alqahtani** [comment]
Thank you @SaraAli26 for the good work. 👍

**Comment by SaraAli26** [comment]
Thank you @alqahtani  :)

**Comment by israelKusayev** [comment]
Hey. How did you manage with RTL md file?
I want to translate to Hebrew but i ran into some issues with the RTL

**Comment by lydiahallie** [comment]
Is this ready to merge?

**Comment by SaraAli26** [comment]
@lydiahallie Yes it's ready to merge.

**Comment by lydiahallie** [comment]
Great! Before merging, could you please add a link in the original `README.md` file that links to this translation?

**Comment by SaraAli26** [comment]
@lydiahallie 
Add link in the original README.md file that links to this translation: Done.

**Comment by lydiahallie** [comment]
Can you please like to the `README_AR.md`?

**Comment by SaraAli26** [comment]
Am sorry, what you mean by lie to the README_AR.md?
@lydiahallie

**Comment by lydiahallie** [comment]
Currently you're linking to ``` https://github.com/SaraAli26/javascript-questions/blob/master/README_AR.md,```  could you update this to  

``` [العربية](./README_AR.md) ``` ? 😄

**Comment by SaraAli26** [comment]
Ahaa, Ok.
Done :) 
@lydiahallie

**Comment by SaraAli26** [comment]
@lydiahallie Added Questions 55 to 63, and its ready to merge :)

**Comment by lydiahallie** [comment]
Awesome thank you! 🚀

**Pull request merged**
