### PR TITLE
NL translations

### PR DESCRIPTION
**Pull request by Tarabass**
Started with dutch translation.

### CODE REVIEW

**Comment by Tarabass** [comment]
Finished the translation :)

**Comment by Tarabass** [comment]
@lydiahallie Where are you waiting for? :P

**Comment by Tarabass** [comment]
@lydiahallie are you speaking Dutch or is Google translate doing a really good job?

**Comment by lydiahallie** [comment]
Haha ik ben Nederlands

**Comment by Tarabass** [comment]
Ak, oké. Dat verklaart een hoop :P

**Pull request merged**
