### PR TITLE
Fix question 145

### PR DESCRIPTION
**Pull request by i-have-no-name**

### CODE REVIEW

**Comment by Pencroff** [comment]
Hey. It seems even this fix would not help, because correct answer id **B**.
Check bellow:
```
$ var person = {
  name: "Lydia Hallie",
  age: 21
}
$ > {name: "Lydia Hallie", age: 21}
$ person[Symbol.iterator]= function *g() { yield Object.values(this) }
$ > ƒ *g() { yield Object.values(this) }
$ [...person]
$ > [Array(2)]
       0: (2) ["Lydia Hallie", 21]
       length: 1
       __proto__: Array(0)
```
And correct answer B would work like:
```
$ var person = {
  name: "Lydia Hallie",
  age: 21
}
$ > {name: "Lydia Hallie", age: 21}
$ person[Symbol.iterator]= function *g() { for (let x in this) yield this[x] }
$ > ƒ *g() { for (let x in this) yield this[x] }
$ [...person]
$ > (2) ["Lydia Hallie", 21]
       0: "Lydia Hallie"
       1: 21
       length: 2
       __proto__: Array(0)
```

**Comment by i-have-no-name** [comment]
> Hey. It seems even this fix would not help, because correct answer id **B**.
> Check bellow:
> 
> ```
> $ var person = {
>   name: "Lydia Hallie",
>   age: 21
> }
> $ > {name: "Lydia Hallie", age: 21}
> $ person[Symbol.iterator]= function *g() { yield Object.values(this) }
> $ > ƒ *g() { yield Object.values(this) }
> $ [...person]
> $ > [Array(2)]
>        0: (2) ["Lydia Hallie", 21]
>        length: 1
>        __proto__: Array(0)
> ```
> 
> And correct answer **B** would work like:
> 
> ```
> $ var person = {
>   name: "Lydia Hallie",
>   age: 21
> }
> $ > {name: "Lydia Hallie", age: 21}
> $ person[Symbol.iterator]= function *g() { for (let x in this) yield this[x] }
> $ > ƒ *g() { for (let x in this) yield this[x] }
> $ [...person]
> $ > (2) ["Lydia Hallie", 21]
>        0: "Lydia Hallie"
>        1: 21
>        length: 2
>        __proto__: Array(0)
> ```

Hey. In your examples you used `yield` but you should use `yield*`

**Comment by Pencroff** [comment]
Yep, you are right (I miss this nuance), but then no right answer in question.

**Comment by lydiahallie** [comment]
Thank you!

**Pull request merged**
