### PR TITLE
add question on shadowing

### PR DESCRIPTION
**Pull request by RitikaJain8818**
Hi, I've added a question that uses the concept of block-scope and shadowing in Javascript.

### CODE REVIEW

**Review by Akashraj161 — COMMENTED** [review]
Looks good to me.

**Comment by RushiCoder** [comment]
nice

**Comment by RitikaJain8818** [comment]
Hi @Akashraj161 
If this looks good, can we merge the PR?

**Comment by RushiCoder** [comment]
Sorry I don't know how to merge PR 

Can you tell me?

**Review by RiczCalixto — APPROVED** [review]

**Review by Akashraj161 — APPROVED** [review]

**Review by Akashraj161 — APPROVED** [review]
This can be merged if someone has the push access to the repository they can merge this PR

**Comment by Abbosbek-cloud** [comment]
It is a good question for JS interviews!

**Comment by jakeherp** [comment]
Based on a chat I had with @lydiahallie we will not add new questions for now. Thanks you nonetheless for the contribution!

**Pull request closed without merging**
