### PR TITLE
Update Some Readme in id-ID

### PR DESCRIPTION
**Pull request by gunturpratama**
greetings,ive contribute to your repository to enliven hacktober fest 2020

### CODE REVIEW

**Review by jakeherp — APPROVED** [review]

**Comment by jakeherp** [comment]
Please resolve merge conflicts

**Comment by gunturpratama** [comment]
i was remove the conflicts sir,thank you

**Comment by gunturpratama** [comment]
i was remove the conflicts sir,thank you

**Comment by gunturpratama** [comment]
Resolve i mean

**Comment by jakeherp** [comment]
There are still unresolved merge conflicts.

**Comment by jakeherp** [comment]
No longer needed.

**Pull request closed without merging**
