### PR TITLE
Spelling mistake

### PR DESCRIPTION
**Pull request by h1t3ndr4**
updated question number 9, greetign changed to greeting

### CODE REVIEW

**Review by jakeherp — APPROVED** [review]

**Comment by zcsongor** [comment]
@jakeherp type was intentional, I think this PR should be reversed

**Comment by jakeherp** [comment]
> @jakeherp typo was intentional, I think this PR should be reverted

You're right, I totally missed that. Opened #662 to revert this change, but need approval. As far as I am aware only @lydiahallie and I can approve, so this might take a while.

**Comment by zcsongor** [comment]
> > @jakeherp typo was intentional, I think this PR should be reverted
> 
> You're right, I totally missed that. Opened #662 to revert this change, but need approval. As far as I am aware only @lydiahallie and I can approve, so this might take a while.

Or I can also create a new PR that reverts this issue, so you can approve it 😅

**Comment by jakeherp** [comment]
@zcsongor Please do!

**Comment by zcsongor** [comment]
@jakeherp all yours 🙂

**Pull request merged**
