### PR TITLE
Fixes to question 76

### PR DESCRIPTION
**Pull request by web20opensource**
Fixes on Question 76 as today the browser accepts the left side of the expression to be started as undefined.

(Other code changes are part of the

### CODE REVIEW

**Comment by WhiteMinds** [comment]
question 76 answer is D，you can try this code:

```javascript
const { age: myAge } = { age: 999 };

console.log(age);
```
the execution result is: `Uncaught ReferenceError: age is not defined`

in origin question code, name is empty string, because name is a property in window

**Review by WhiteMinds — CHANGES_REQUESTED** [review]
answer not A

**Review by jakeherp — CHANGES_REQUESTED** [review]
Running this, it actually returns `undefined` for me, so answer C should be correct.

**Comment by WhiteMinds** [comment]
> Running this, it actually returns `undefined` for me, so answer C should be correct.

Because name is window.name, so it's already defined, but if you running on NodeJS or other javascript engine, the answer is D.

I think the title is misleading because it does not clarify the operating environment.

you can try running my code:
```javascript
const { age: myAge } = { age: 999 };

console.log(age);
```

**Review by jakeherp — APPROVED** [review]

**Pull request merged**
