### PR TITLE
changed the name of the readme

### PR DESCRIPTION
**Pull request by luciacenetiempo**
changed the name of the readme file from readme-it to readme to make all links work in other languages

### CODE REVIEW

**Review by jakeherp — CHANGES_REQUESTED** [review]
@luciacenetiempo there are no changes in this PR

**Comment by luciacenetiempo** [comment]
hi @jakeherp I just changed the filename from README-IT.md to README.md
so I only removed "-IT" for consistency with internal links.

Can't see the change?

**Review by luciacenetiempo — COMMENTED** [review]
Seems to be ok on my side!

**Review by jakeherp — APPROVED** [review]
Sorry, my bad! Didn't realise the file name was updated - Gitlab makes this a bit easier to spot than Github 😄

**Comment by jakeherp** [comment]
@luciacenetiempo can you resolve merge conflicts, so I can re-approve and get this merged? 🙂

**Comment by luciacenetiempo** [comment]
@jakeherp this is a strange situation. I just renamed the file, so I no longer have the README-IT.md one
do you have any idea how to resolve this conflict?

Schermata 2022-08-29 alle 12 36 47

**Comment by jakeherp** [comment]
> @jakeherp this is a strange situation. I just renamed the file, so I no longer have the README-IT.md one do you have any idea how to resolve this conflict?
> 
> Schermata 2022-08-29 alle 12 36 47

I suppose if it doesn't create the file again, the easiest way might be to undo your change (i.e. rename it back to `README-IT.md`, that way you should be able to merge the changes from `master` and then rename it again)

**Comment by luciacenetiempo** [comment]
@jakeherp ok cool your solution worked 💪

**Pull request merged**
