### PR TITLE
Add translate the questions 79-86 to Korean.

### PR DESCRIPTION
**Pull request by sweetmilkys**

### CODE REVIEW

**Comment by lydiahallie** [comment]
Can you please change it to the new folder structure? 😃

**Comment by sweetmilkys** [comment]
> Can you please change it to the new folder structure? 😃

Why not?
but I didn't update your new questions yet. 
So please allow me let you know when I add new one. Thanks :)

**Comment by lydiahallie** [comment]
Thanks! Can I merge this?

**Comment by sweetmilkys** [comment]
> Thanks! Can I merge this?

Yes! 
I'm busy these days, so I'm going to be late.

**Pull request merged**
